package tcpserver.src.mavlinklib.command.camera.custom.list;


public enum CUSTOM_CAMERA_TYPE {  // CAMERA_MODE
	AMP_EO(0),
	AMP_IR(1),
	PRENUW_SMALLCAM_STOW_FACE_MODE(0),  // Stow
	PRENUW_SMALLCAM_PILOT_MODE(1),
	PRENUW_SMALLCAM_HOLD_COORDICATE_MODE(2),
	PRENUW_SMALLCAM_OBSERVATION_MODE(3),
	PRENUW_SMALLCAM_LOCAL_POSITON_MODE(4),
	PRENUW_SMALLCAM_GLOBAL_POSITON_MODE(5),
	PRENUW_SMALLCAM_GRR_MODE(6),
	PRENUW_SMALLCAM_TRACKING_MODE(7),
	PRENUW_SMALLCAM_EPR_MODE(8),
	PRENUW_SMALLCAM_NADIR_BELOW_MODE(9),  // BELOW
	PRENUW_SMALLCAM_NADIR_SCAN_MODE(10),
	PRENUW_SMALLCAM_2D_SCAN_MODE(11),
	PRENUW_SMALLCAM_POINT_COORDINATE_MODE(12),
	PRENUW_SMALLCAM_UNSTABILIZED_POSITION_MODE(13);
	// TODO..
	public final int rawStateData;

	CUSTOM_CAMERA_TYPE(int val) {
		this.rawStateData = val;
	}
}